---
title: "ABM Analysis - ASD Interaction"
author: "Bertram Hojer"
date: "5/6/2020"
output: html_document
editor_options: 
  chunk_output_type: console
---

# Importing libraries
```{r libraries}
setwd("/Users/bertram/Desktop/folders/Uni/4th/SocCult-Exam/ABM/Social-Cultural-Dynamics")

library(pacman)
p_load(tidyverse, brms)
```


# Loading ABM data
```{r Loading data}
# loading simulated training data
batch_data <- read_csv("batch_data.csv")

batch_data$Diagnosis <- as.numeric(batch_data$AgentId)
batch_data$Diagnosis <- ifelse(batch_data$Diagnosis < 25, "ASD", "TD")
batch_data$label <- ifelse(batch_data$Diagnosis == "ASD", 0, 1)


batch_data <- batch_data %>% 
  mutate(
    change_IQR = scale(change_IQR),
    activity = scale(activity),
    change_MAD = scale(change_MAD),
    change_PauseFreq = scale(change_PauseFreq),
    change_Speechrate = scale(change_Speechrate),
    conversation_time = scale(conversation_time),
    interaction_time = scale(interaction_time),
    interactions = scale(interactions),
    ID = AgentId
  )

batch_data <- batch_data %>% 
  mutate(
    Run = as.numeric(Run)
  ) %>% 
  filter(Run < 200)
```


# Specify Bayesian formulas
```{r}
IQR_f <- bf(
  change_IQR ~ 1 + Diagnosis + (1 | ID)
)

activity_f <- bf(
  activity ~ 1 + Diagnosis + (1 | ID)
)

MAD_f <- bf(
  change_MAD ~ 1 + Diagnosis + (1 | ID)
)

PauseFreq_f <- bf(
  change_PauseFreq ~ 1 + Diagnosis + (1 | ID)
)

Speechrate_f <- bf(
  change_Speechrate ~ 1 + Diagnosis + (1 | ID)
)

conversation_time_f <- bf(
  conversation_time ~ 1 + Diagnosis + (1 | ID)
)

interaction_time_f <- bf(
  interaction_time ~ 1 + Diagnosis + (1 | ID)
)

interactions_f <- bf(
  interactions ~ 1 + Diagnosis + (1 | ID)
)
```


# Specifying priors
```{r priors}
get_prior(IQR_f, data = batch_data)

prior <- c(
  prior(normal(0, .1), class = Intercept),
  prior(normal(0, .01), class = b),
  prior(normal(0, .01), class = sd),
  prior(normal(.5, .3), class = sigma)
)
```


# Prior predictive model
```{r}
IQR_pc <- brm(
  IQR_f,
  data = batch_data,
  family = gaussian,
  prior = prior,
  sample_prior = "only",
  chains = 4,
  cores = 2
)


pp_check(IQR_pc, nsamples = 100)

IQR_m <- brm(
  IQR_f,
  data = batch_data,
  family = gaussian,
  prior = prior,
  sample_prior = T,
  chains = 4,
  cores = 2
)

pp_check(IQR_m, nsamples = 100)

summary(IQR_m)
```


